version: "3.7"
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/var/lib/mongo/data/db
    ports:
      - "27017:27017"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      swarm_net:
        ipv4_address: 172.28.1.1
  web-api:
    image: 127.0.0.1:5000/web-api
    build: ./API
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 2
    ports:
      - "49160:8080"
    networks:
      swarm_net:
        ipv4_address: 172.28.1.2
  web-app:
    image: 127.0.0.1:5000/web-app
    build: ./Web_App/webApp
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 2
    depends_on:
      - mongo
      - web-api
    ports:
      - "8080:80"
    networks:
      swarm_net:
        ipv4_address: 172.28.1.3
volumes:
  mongo_data:
    external: true

networks:
    swarm_net:
      driver: overlay
      ipam:
        config:
            - subnet: 172.28.0.0/16